function loadGame() { document.write("<table border=0 cellpadding=4 cellspacing=0 bgcolor=#663300><tr><td bgcolor=#000000>"); document.write("<table border=0 cellpadding=0 cellspacing=2 bgcolor=#663300><tr>"); for (j=0; j < MaxX; j++) { document.write("<td valign=middle width=12>"); for (i=0; i < MaxY-1+j%2; i++) { document.write("<IMG src=img/shroom0.gif border=0>"); } document.write("</td>"); } document.write("</tr></table></td></tr></table>");
if (navigator.appName == "Konqueror") { document.write("</td><td>"); document.write("<input width=0 height=0 style='width:0; height:0' name='KeyCatch' onBlur='KeyCatchFocus()' onKeyUp='KeyCatchChange()'>"); KeyCatchFocus(); IsHideFocus=false; }
function KeyCatchFocus() { setTimeout("document.forms[0].KeyCatch.focus()",100); }
function KeyCatchChange() { var vv=""+document.forms[0].KeyCatch.value; if (vv=="") return; KeyDown(vv.charCodeAt(0)); document.forms[0].KeyCatch.value=""; } document.close(); }
if (navigator.appName != "Microsoft Internet Explorer") { document.captureEvents(Event.KEYDOWN); document.onkeydown = NetscapeKeyDown; } else {}
function NetscapeKeyDown(key) { KeyDown(key.which); }  
var i, j, isEnd, MaxX=12, MaxY=17, NextCol, Col, Score, Lines, IsHideFocus=true; PosX=new Array(4); PosY=new Array(4); Fld = new Array(MaxX); for (i=0; i < MaxX; i++) { Fld[i]=new Array(MaxY); }  RFld=new Array(MaxY); Pic=new Array(3); Pic[0]=new Image(); Pic[0].src="img/shroom2.gif"; Pic[1]=new Image(); Pic[1].src="img/shroom1-1.gif"; Pic[2]=new Image(); Pic[2].src="img/shroom0.gif"; Pic[3]=new Image(); Pic[3].src="img/shroom1-0.gif"; ShroomedX=new Array(9); ShroomedY=new Array(9); ShroomedX[0]=new Array(0,1,1,2); ShroomedY[0]=new Array(1,0,1,1); ShroomedX[1]=new Array(0,1,1,1); ShroomedY[1]=new Array(1,0,1,2); ShroomedX[2]=new Array(1,1,1,1); ShroomedY[2]=new Array(0,1,2,3); ShroomedX[3]=new Array(0,1,1,2); ShroomedY[3]=new Array(0,0,1,0); ShroomedX[4]=new Array(0,0,1,2); ShroomedY[4]=new Array(0,1,0,0); ShroomedX[5]=new Array(0,0,1,1); ShroomedY[5]=new Array(1,2,0,1); ShroomedX[6]=new Array(1,1,2,2); ShroomedY[6]=new Array(0,1,1,2); ShroomedX[7]=new Array(0,1,1,1); ShroomedY[7]=new Array(2,0,1,2); ShroomedX[8]=new Array(1,1,1,2); ShroomedY[8]=new Array(0,1,2,2);
function KeyDown(whichkey) { if (isEnd) { return; } else {} if (PosY<0) { return; } else {} if (whichkey==37 || whichkey==52 || whichkey==65460) { Left(); } else if (whichkey==39 || whichkey==54 || whichkey==65462) { Right(); } else if (whichkey==38 || whichkey==56 || whichkey==65464) { Rotate(); } else if (whichkey==40 || whichkey==50 || whichkey==65458) { Down(); } else {}}
function New() { isEnd=true; setTimeout("Init(true)",100); }
function Init(nn) { isEnd=false; if (nn) { for (i=0; i<MaxX; i++) { for (j=0; j<MaxY; j++) { Fld[i][j]=0; } } PosY[0]=-1; Score=0; Level=1; Lines=0; window.document.shroomForm.Score.value = Score; window.document.shroomForm.Level.value = Level; window.document.shroomForm.Lines.value = Lines; RefreshShroom(); NextCol=Math.floor(Math.random()*100)%9; } setTimeout("Go()",75*(11-Level)); HideFocus(); }
function Go(){ if (isEnd) { return; } else {} var nn, mm=MaxX*MaxY-Math.floor((MaxX+1)/2); if (PosY[0]<0) { Col=NextCol; NextCol=Math.floor(Math.random()*100)%9; for (nn=mm; nn<mm+10; nn++) { document.images[nn].src = Pic[2].src; } for (nn=0; nn<4; nn++) { document.images[mm+ShroomedX[NextCol][nn]*4-Math.floor((ShroomedX[NextCol][nn]+1)/2)+ShroomedY[NextCol][nn]].src = Pic[3].src; } for (nn=0; nn<4; nn++) { PosX[nn]=ShroomedX[Col][nn]+6; PosY[nn]=ShroomedY[Col][nn]+1; if (Fld[PosX[nn]][PosY[nn]]>0) { isEnd=true; } else {} } if (isEnd) { if (CanShift(0,-1)) { for (nn=0; nn<4; nn++) { document.images[PosX[nn]*MaxY-Math.floor((PosX[nn]+1)/2)+PosY[nn]-1].src = Pic[3].src; } } updateScore(Score); return; } for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=1; document.images[PosX[nn]*MaxY-Math.floor((PosX[nn]+1)/2)+PosY[nn]].src = Pic[1].src; }} else { for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=0; } if (CanShift(0,1)) { for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=1; } Shift(0,1); } else { for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=1; } PosY[0]=-1; Remove(); window.document.shroomForm.Score.value = Score; window.document.shroomForm.Level.value = Level; window.document.shroomForm.Lines.value = Lines; }} setTimeout("Go()",75*(11-Level)); }
function GetFld(xx, yy) { if (xx<0) { return(-1); } else {} if (xx>=MaxX) { return(-1); } else {} if (yy<0) { return(-1); } else {} if (yy>=MaxY-1+xx%2) { return(-1); } else {} return(Fld[xx][yy]); }
function Rotate() { if (isEnd) { return; } else {} var nn, xxm=0, yym=0, xx0, yy0, xx1, yy1, rr=0; var aa=0.5, bb=1, cc=-0.75, dd=0.5; for (nn=0; nn<4; nn++) { xxm+=PosX[nn]; yym+=PosY[nn]-(PosX[nn]%2)/2; Fld[PosX[nn]][PosY[nn]]=0; } xxm=Math.round(xxm/4); yym=Math.round(yym/4+(xxm%2)/2); if (xxm%2==1) { for (nn=0; nn<4; nn++) { xx0=PosX[nn]-xxm; yy0=PosY[nn]-yym+(Math.abs(PosX[nn]-xxm)%2)/2; xx1=Math.round(xx0*aa+yy0*bb+xxm); yy1=Math.round(xx0*cc+yy0*dd-(Math.abs(xx1-xxm)%2)/2+yym); if (GetFld(xx1,yy1)!=0) { rr++; } else {}} } else { for (nn=0; nn<4; nn++) { xx0=PosX[nn]-xxm; yy0=PosY[nn]-yym-(Math.abs(PosX[nn]-xxm)%2)/2; xx1=Math.round(xx0*aa+yy0*bb+xxm); yy1=Math.round(xx0*cc+yy0*dd+(Math.abs(xx1-xxm)%2)/2+yym); if (GetFld(xx1,yy1)!=0) { rr++; } else {} } } if (rr>0) { for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=1; } return; }   for (nn=0; nn<4; nn++) { document.images[PosX[nn]*MaxY-Math.floor((PosX[nn]+1)/2)+PosY[nn]].src = Pic[0].src; } if (xxm%2==1) { for (nn=0; nn<4; nn++) { xx0=PosX[nn]-xxm; yy0=PosY[nn]-yym+(Math.abs(PosX[nn]-xxm)%2)/2; xx1=Math.round(xx0*aa+yy0*bb+xxm); yy1=Math.round(xx0*cc+yy0*dd-(Math.abs(xx1-xxm)%2)/2+yym); PosX[nn]=xx1; PosY[nn]=yy1; } } else { for (nn=0; nn<4; nn++) { xx0=PosX[nn]-xxm; yy0=PosY[nn]-yym-(Math.abs(PosX[nn]-xxm)%2)/2; xx1=Math.round(xx0*aa+yy0*bb+xxm); yy1=Math.round(xx0*cc+yy0*dd+(Math.abs(xx1-xxm)%2)/2+yym); PosX[nn]=xx1; PosY[nn]=yy1; } }   for (nn=0; nn<4; nn++) { document.images[PosX[nn]*MaxY-Math.floor((PosX[nn]+1)/2)+PosY[nn]].src = Pic[1].src; }}
function Left() { if (isEnd) { return; } else {} if (PosY[0]<0) { return; } else {} for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=0; } if (CanShift(-1,0)) { for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=1; } Shift(-1,0); } else { for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=1; } } }
function Right() { if (isEnd) { return; } else {} if (PosY[0]<0) { return; } else {} for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=0; } if (CanShift(1,0)) { for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=1; } Shift(1,0); } else { for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=1; } }}
function Down() { if (isEnd) { return; } else {} if (PosY[0]<0) { return; } else {} var dd=0; for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=0; } while (CanShift(0,dd+1)) { dd++; } for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=1; } if (dd>0) { Shift(0, dd); } else {}}
function CanShift(xx, yy) { var nn, cc=true, xxn, yyn; for (nn=0; nn<4; nn++) { xxn=PosX[nn]+xx; if (xxn<0) { return(false); } else {} if (xxn>=MaxX) { return(false); } else {} yyn=PosY[nn]+yy; if (xx!=0) { yyn+=xxn%2; } else {} if (yyn>=MaxY-1+xxn%2) { return(false); } else {} if (Fld[xxn][yyn]>0) { return(false); } else {} } return(true); }
function Shift(dx, dy) { var nn; for (nn=0; nn<4; nn++) { Fld[PosX[nn]][PosY[nn]]=0; document.images[PosX[nn]*MaxY-Math.floor((PosX[nn]+1)/2)+PosY[nn]].src = Pic[0].src; } for (nn=0; nn<4; nn++) { PosX[nn]+=dx; PosY[nn]+=dy; if (dx!=0) { PosY[nn]+=PosX[nn]%2; } else {} Fld[PosX[nn]][PosY[nn]]=1; document.images[PosX[nn]*MaxY-Math.floor((PosX[nn]+1)/2)+PosY[nn]].src = Pic[1].src; }}
function Remove() { var xx, yy, nn=0; Score+=Level; for (yy=0; yy<MaxY; yy++) { RFld[yy]=1; } for (xx=0; xx<MaxX; xx++) { for (yy=0; yy<MaxY-1; yy++) { if (Fld[xx][yy]==0) { RFld[yy]=0; } else {} }} for (yy=MaxY-2; yy>=0; yy--) { if (RFld[yy]>0) { nn++; for (xx=0; xx<MaxX; xx++) { Fld[xx][yy]=0; } } else { if (nn>0) { for (xx=0; xx<MaxX; xx++) { Fld[xx][yy+nn]=Fld[xx][yy]; Fld[xx][yy]=0; }}}} Score+=25*nn; Lines+=nn; if ((Score>=(250*Level*Level))&&(Level<10)) { Level++; } else {} if (nn>0) { RefreshShroom(); } else {}}
function RefreshShroom() { for (i=0; i < MaxX; i++) { for (j=0; j < MaxY-1+i%2; j++) { window.document.images[i*MaxY-Math.floor((i+1)/2)+j].src = Pic[Fld[i][j]].src; } } }
function HideFocus() { if (IsHideFocus) { document.shroomForm.Score.focus(); document.shroomForm.Score.blur(); } }
function start() { document.getElementById("startDiv").style.display="none"; document.getElementById("restartDiv").style.display="block"; New(); }
function endnow() { document.getElementById("startDiv").style.display="block"; document.getElementById("restartDiv").style.display="none"; isEnd=true; }